name: arrhythmia-vision
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - altair=5.5.0
  - joblib=1.4.2
  - jupyter=1.1.1
  - matplotlib=3.10.0
  - numpy=2.2.5
  - pandas=2.2.3
  - pip=25.1
  - scikit-learn=1.6.1
  - seaborn=0.13.2
  - glob2=0.7
  - openpyxl=3.1.5
  - tqdm=4.67.1
  - opencv=4.10.0
  - optuna=4.4.0
  - plotly=6.0.1
  - torchinfo=1.8.0
  - pip:
      - ecg-plot==0.2.8
      - lmdb==1.6.2
      - thop==0.1.1-2209072238
      - torchsummary==1.5.1

# NOTE: For pytorch and torchvision are intentionally excluded from the list to avoid compatibility issues.
# Please install pytorch and torchvision together. Refer to the website below and choose the appropirate installer based on your OS and GPU.
#    https://pytorch.org/get-started/locally/


# --- FOR REFERENCE AND REPRODUCIBILITY ATTEMPTS ----
# Local (2023 Macbook, M3): pytorch=2.5.1 (build: gpu_mps_py312hbd1d365_204)  |  torchvision=0.20.1 (build: mps_py312h620d032_102)
# Remote HPC (NVIDIA A100): torch=2.6.0 (build: pypi_0)  |  torchvision=0.21.0 (build: pypi_0)  |  nvidia-cudnn-cu12=9.1.0.70 (build: pypi_0)